[tool.mypy]
python_version = "3.8"
strict = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "glymur.*"

[tool.ruff]
fix = true
force-exclude = true
select = [
    "F401", # Remove unused imports
    "I", # Sort imports
    "UP", # Update Python syntax
]
target-version = "py38"
isort.known-first-party = [
    "hipct_data_tools",
]
mccabe.max-complexity = 18
pep8-naming.classmethod-decorators = [
    "classmethod",
    "pydantic.validator",
]

[tool.tomlsort]
all = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
overrides."project.classifiers".inline_arrays = false
overrides."tool.coverage.paths.source".inline_arrays = false
